env:
  BUILDKITE_PLUGINS_ALWAYS_CLONE_FRESH: true

steps:
  - label: ":bazel: Test the things"
    command: bazel test //... --build_event_json_file build-events.json
    plugins:
      - https://github.com/mcncl/bazel-annotate-buildkite-plugin.git:
          bep_file: bazel-events.json
