env:
  BUILDKITE_PLUGINS_ALWAYS_CLONE_FRESH: true

steps:
  - label: ":java:"
    command: which java && echo $$JAVA_HOME
  - wait: ~
  - label: ":bazel: Test the things"
    command: bazel test //... --build_event_json_file build-events.json && ls -alh
    plugins:
      - https://github.com/mcncl/bazel-annotate-buildkite-plugin.git:
          bep_file: bazel-events.json
