env:
  BUILDKITE_PLUGINS_ALWAYS_CLONE_FRESH: true
  JAVA_HOME: "/usr/bin/java"

steps:
  - label: ":bazel: Test the things"
    command: bazel test //... --java_runtime_version=remotejdk_11 --build_event_json_file build-events.json && ls -alh
    plugins:
      - https://github.com/mcncl/bazel-annotate-buildkite-plugin.git:
          bep_file: bazel-events.json
